import type { JSONContent } from "@tiptap/core";

/** Empty TipTap doc shape. */
export function emptyContractDoc(): JSONContent {
  return {
    type: "doc",
    content: [{ type: "paragraph" }],
  };
}

/**
 * Starting draft for likeness / publicity-style licenses.
 * Generic structure only — not legal advice; parties should have counsel review
 * before execution. Tailored to the brand’s request fields from Muhr.
 */
export function defaultContractDocFromRequest(input: {
  brand_name: string;
  brand_company: string | null;
  intended_use: string;
  duration_days: number;
  budget_inr: number | null;
  channels: string[];
  territories: string[];
}): JSONContent {
  const licensee = `${input.brand_name}${input.brand_company ? ` (${input.brand_company})` : ""}`;

  const lines: string[] = [
    "CONTENT / LIKENESS & PUBLICITY LICENSE AGREEMENT (DRAFT)",
    "",
    "IMPORTANT — READ BEFORE USE",
    "This is a generic draft generated by Muhr from the brand’s request summary. It is NOT legal advice, NOT guaranteed to be enforceable in any court, and NOT specific to your facts or jurisdiction. You must have a qualified lawyer review, adapt, and finalize this agreement before signing. Muhr is not a law firm.",
    "",
    "1. PARTIES",
    "1.1 Licensor (Creator): [INSERT FULL LEGAL NAME AND ADDRESS]",
    `1.2 Licensee: ${licensee}`,
    "[INSERT LICENSEE LEGAL ENTITY NAME, ADDRESS, AND SIGNATORY TITLE]",
    "",
    "2. BACKGROUND",
    "The Licensor holds rights in their name, image, likeness, voice, and related personality rights and content as described in this Agreement. The Licensee wishes to use those rights for the purposes summarized below.",
    "",
    "3. GRANT OF RIGHTS",
    "3.1 Subject to the terms of this Agreement, the Licensor grants the Licensee a limited, non-exclusive licence (unless otherwise stated) to use the Licensor’s likeness and approved materials solely for the following purpose(s):",
    input.intended_use,
    "3.2 Channels (as discussed):",
    (input.channels?.length ? input.channels.join(", ") : "[To be specified]") as string,
    "3.3 Territory:",
    (input.territories?.length ? input.territories.join(", ") : "[To be specified]") as string,
    "3.4 The Licensor reserves all rights not expressly granted. Moral rights and personality rights remain with the Licensor to the extent they cannot be waived under applicable law.",
    "",
    "4. TERM",
    `4.1 Initial term discussed: approximately ${input.duration_days} days from the Effective Date (define Effective Date below).`,
    "4.2 Renewal / extension: [solely as agreed in writing by both parties]",
    "4.3 Termination: [insert events for early termination, cure periods, and effect on accrued obligations]",
    "",
    "5. COMPENSATION",
    input.budget_inr != null
      ? `5.1 Fees discussed: ₹${input.budget_inr.toLocaleString("en-IN")} (INR), subject to final written agreement, invoicing, and taxes.`
      : "5.1 Fees: [insert amount, currency, payment milestones, and taxes]",
    "5.2 Late payment: [if applicable]",
    "",
    "6. APPROVALS & DELIVERABLES",
    "6.1 Pre-approval: The Licensee shall obtain the Licensor’s prior written approval for any use that departs materially from agreed creative, copy, or context.",
    "6.2 Samples: On reasonable request, the Licensee shall provide copies or links of published materials.",
    "",
    "7. INTELLECTUAL PROPERTY",
    "7.1 The Licensor retains ownership of all pre-existing rights, including name, image, likeness, voice, and underlying content.",
    "7.2 Any new materials incorporating the Licensor’s likeness remain subject to the Licensor’s underlying rights unless otherwise agreed in writing.",
    "",
    "8. REPRESENTATIONS & WARRANTIES",
    "8.1 Each party represents it has authority to enter this Agreement.",
    "8.2 The Licensor represents, to the best of their knowledge, they have the right to grant the licence described herein for the agreed uses.",
    "8.3 The Licensee represents its use will comply with applicable advertising, consumer, data-protection, and platform rules.",
    "",
    "9. INDEMNITY",
    "9.1 [Insert mutual or one-way indemnities as advised by counsel, caps, and procedures]",
    "",
    "10. LIMITATION OF LIABILITY",
    "10.1 [Insert exclusions and caps as advised by counsel]",
    "",
    "11. CONFIDENTIALITY",
    "11.1 The parties shall keep the terms of this Agreement and non-public business information confidential, subject to standard exceptions (legal requirement, professional advisers, etc.).",
    "",
    "12. DATA PROTECTION",
    "12.1 [If personal data is processed, insert roles (controller/processor), purposes, and safeguards as required in your jurisdiction]",
    "",
    "13. GOVERNING LAW & DISPUTES",
    "13.1 This Agreement shall be governed by the laws of [INSERT JURISDICTION — e.g. India].",
    "13.2 Disputes shall be resolved by [courts of INSERT CITY / arbitration as advised by counsel].",
    "",
    "14. MISCELLANEOUS",
    "14.1 Entire agreement; amendments in writing.",
    "14.2 Assignment: [restrictions as advised]",
    "14.3 Notices: [addresses and email for formal notices]",
    "14.4 Severability; waiver; counterparts; electronic signatures if permitted locally.",
    "",
    "15. EXECUTION (OFF-MUHR)",
    "Final execution (wet ink, e-sign platform, or counsel-managed signing) is your responsibility. Export this draft from Muhr (Word/PDF), finalize in your own systems, and retain executed copies.",
    "",
    "SIGNATURE BLOCKS (to be completed on the final version)",
    "Licensor: ________________________________  Name & title: ________________________________  Date: __________",
    "Licensee: _______________________________  Name & title: ________________________________  Date: __________",
  ];

  return {
    type: "doc",
    content: lines.map((line) => ({
      type: "paragraph",
      ...(line
        ? {
            content: [{ type: "text", text: line }],
          }
        : {}),
    })),
  };
}
